# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='norwegain_name',
            new_name='norwegian_name',
        ),
    ]
