# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0002_auto_20161214_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flora.Plant'),
        ),
    ]
