# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 13:09
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0003_auto_20161219_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(upload_to=b''),
        ),
    ]
