# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0004_auto_20170103_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to=b''),
        ),
    ]
